version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # want to match the engine version
      - dependency-name: "@types/vscode"
